# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13                         # https://pyreadiness.org/3.9/
  - pip=22.1.2                            # https://pip.pypa.io/en/stable/news/
  - pytorch=1.13.1                        # https://anaconda.org/conda-forge/pytorch
  - tesseract=5.3.0                       # https://anaconda.org/conda-forge/tesseract
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==22.0.0              # https://rpaframework.org/releasenotes.html
      - transformers==4.26.1              # https://pypi.org/project/transformers/
      - rpaframework-recognition==5.1.0   # https://pypi.org/project/rpaframework-recognition/
